-- DROP VIEW_PFOL
DROP VIEW IF EXISTS VIEW_PFOL;

-- CREATE VIEW_PFOL
CREATE VIEW VIEW_PFOL AS
SELECT pl.PFOL_SN, pl.PFOL_NM, pl.START_DT, pl.END_DT, pl.PERIOD, pl.INTRO
    , pl.MEM_CNT, pl.CONTRIBUTION
    , GROUP_CONCAT(DISTINCT st.ST_NM)  AS STACK
    , GROUP_CONCAT(DISTINCT r.ROLE_NM) AS ROLE
    , pl.SERVICE_STTS
    , pl.`RESULT`
    , url.URL
    , GROUP_CONCAT( DISTINCT pm.URL) as MEDIA
FROM TB_PFOL pl
LEFT JOIN TB_PF_PFOL pp ON pl.PFOL_SN = pp.PFOL_SN
LEFT JOIN TB_PFOL_ST ps ON ps.PFOL_SN = pp.PFOL_SN
LEFT JOIN TB_ST st ON st.ST_SN = ps.ST_SN
LEFT JOIN TB_PFOL_ROLE plR ON plR.PFOL_SN = pl.PFOL_SN
LEFT JOIN TB_ROLE r ON r.ROLE_SN = plR.ROLE_SN
LEFT JOIN TB_PFOL_MEDIA pm ON pl.PFOL_SN = pm.PFOL_SN AND pm.MAIN_YN = 1
left join TB_PFOL_URL plU ON plU.PFOL_SN = pl.PFOL_SN
left join TB_URL url on plU.URL_SN = url.URL_SN
GROUP BY pl.PFOL_SN
ORDER BY pl.START_DT ASC;

-- SELECT VIEW_PFOL
SELECT * FROM VIEW_PFOL;